### PR TITLE
Fix propagation direction and time

### PR DESCRIPTION
**Pull request by carinakanitz**
Corrected the propagation time by the refractive index of the medium
Corrected the calculation of the direction of a ray traversing a boundary from above

### CODE REVIEW

**Comment by anelles** [comment]
The tests fail on some clang business. I think this would be up to @TobiasWinchen to have a look at this, as I never looked into the RadioPropa tests.

**Comment by TobiasWinchen** [comment]
The reason for the failed tests here is in the travis config. See PR #10.

**Comment by anelles** [comment]
After @TobiasWinchen has fixed this, @carinakanitz feel free to merge to master.

**Comment by anelles** [comment]
@carinakanitz if you merge the master into this branch, the tests should run fine again and you can merge the pull request.

**Pull request merged**
